#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Nov 21 17:27:58 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 2bd1f9c1a5a04632b86fc733aeb8f5f4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_Multiplexer_behav xil_defaultlib.tb_Multiplexer xil_defaultlib.glbl -log elaborate.log"
xelab -wto 2bd1f9c1a5a04632b86fc733aeb8f5f4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_Multiplexer_behav xil_defaultlib.tb_Multiplexer xil_defaultlib.glbl -log elaborate.log

